baseURL: "/"
title: "My Personnal Documentation"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
languages:
  en:
    lang: "en"
    languageName: "English"
    weight: 2
MetaDataFormat: "yaml"
theme: hugo-theme-learn